"""add weather adn traffic to encounter table

Revision ID: 0ce60b242aba
Revises: cd777635c754
Create Date: 2023-10-27 15:38:21.905858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ce60b242aba'
down_revision = 'cd777635c754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_encounter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weatherReminder', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('trafficReminder', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_encounter', schema=None) as batch_op:
        batch_op.drop_column('trafficReminder')
        batch_op.drop_column('weatherReminder')

    # ### end Alembic commands ###
