"""add chief complaint table

Revision ID: 23d37fdd851c
Revises: 2c8f2c4469c4
Create Date: 2023-10-26 10:39:32.219190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d37fdd851c'
down_revision = '2c8f2c4469c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chiefcomplaint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('GS', sa.Boolean(), nullable=True),
    sa.Column('cardiology', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chiefcomplaint')
    # ### end Alembic commands ###
