"""add columns to suggested appointments

Revision ID: 29ae1a307132
Revises: 94bd930872bf
Create Date: 2023-11-03 10:48:27.340427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ae1a307132'
down_revision = '94bd930872bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggested_appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_reminder', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('appointment_reminder', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('weather_reminder', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('traffic_reminder', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggested_appointments', schema=None) as batch_op:
        batch_op.drop_column('traffic_reminder')
        batch_op.drop_column('weather_reminder')
        batch_op.drop_column('appointment_reminder')
        batch_op.drop_column('booking_reminder')

    # ### end Alembic commands ###
