"""add appointmen type and procedure type table

Revision ID: 2c8f2c4469c4
Revises: f5b89cb66129
Create Date: 2023-10-26 09:40:29.565237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c8f2c4469c4'
down_revision = 'f5b89cb66129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointmenttype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('rate', sa.Numeric(), nullable=True),
    sa.Column('booking_reminder', sa.String(length=255), nullable=True),
    sa.Column('appointment_reminder', sa.String(length=255), nullable=True),
    sa.Column('weather_reminder', sa.String(length=255), nullable=True),
    sa.Column('traffic_reminder', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proceduretype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('rate', sa.Numeric(), nullable=True),
    sa.Column('prior_procedure_reminder', sa.String(length=255), nullable=True),
    sa.Column('post_procedure_reminder', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proceduretype')
    op.drop_table('appointmenttype')
    # ### end Alembic commands ###
