"""add event a and b and c

Revision ID: 6476631f3b0e
Revises: 29ae1a307132
Create Date: 2023-11-03 11:39:56.754936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6476631f3b0e'
down_revision = '29ae1a307132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggested_appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id_a', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('event_id_b', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('event_id_c', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggested_appointments', schema=None) as batch_op:
        batch_op.drop_column('event_id_c')
        batch_op.drop_column('event_id_b')
        batch_op.drop_column('event_id_a')

    # ### end Alembic commands ###
