"""add new table suggested appointments

Revision ID: 94bd930872bf
Revises: 0ce60b242aba
Create Date: 2023-11-03 10:41:08.469673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94bd930872bf'
down_revision = '0ce60b242aba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggested_appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=True),
    sa.Column('date1', sa.Date(), nullable=True),
    sa.Column('time1', sa.Time(), nullable=True),
    sa.Column('date2', sa.Date(), nullable=True),
    sa.Column('time2', sa.Time(), nullable=True),
    sa.Column('date3', sa.Date(), nullable=True),
    sa.Column('time3', sa.Time(), nullable=True),
    sa.Column('approved_date', sa.Date(), nullable=True),
    sa.Column('approved_time', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suggested_appointments')
    # ### end Alembic commands ###
