"""update chief complaint

Revision ID: cd777635c754
Revises: 23d37fdd851c
Create Date: 2023-10-26 10:45:52.566979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd777635c754'
down_revision = '23d37fdd851c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chiefcomplaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('general_surgery', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('dentistry', sa.Boolean(), nullable=True))
        batch_op.drop_column('GS')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chiefcomplaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('GS', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('dentistry')
        batch_op.drop_column('general_surgery')

    # ### end Alembic commands ###
